apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mifos-x
spec:
  destination:
    name: ''
    namespace: banking-demo
    server: https://kubernetes.default.svc
  source:
    path: .
    repoURL: https://github.com/linusali/vm-gitops-demo.git
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: webserver.replicas
          value: "3"
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
