kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: argocd-application-controller-role
  namespace: banking-demo
rules:
  - verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
    apiGroups:
      - apps
      - ''
      - k8s.cni.cncf.io
      - kubevirt.io
      - route.openshift.io
    resources:
      - services
      - pods
      - configmaps
      - secrets
      - deployments
      - network-attachment-definitions
      - virtualmachines
      - routes
      - statefulsets
