apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-demo
spec:
  destination:
    namespace: gitops-demo
    server: https://kubernetes.default.svc
  source:
    path: .
    repoURL: https://github.com/linusali/vm-gitops-demo.git
    targetRevision: simple
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
