apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ $.Values.database.storage }}
  storageClassName: {{ required "You must provide a valid StorageClass name in values.yaml" $.Values.database.storageclass }}
  volumeMode:  Filesystem