{{- $rootPasswordValue := (randAlpha 16) | b64enc | quote }}
{{- $passwordValue := (randAlpha 16) | b64enc | quote }}
{{- $dbUserValue := "mifosuser" |b64enc | quote }}
{{- $dbNameValue := "mifosdb" |b64enc | quote }}

{{- $secret := (lookup "v1" "Secret" .Release.Namespace "mariadb") }}
{{- if $secret }}
{{- $rootPasswordValue = index $secret.data "database-root-password" }}
{{- $passwordValue = index $secret.data "database-password" }}
{{- $dbUserValue = index $secret.data "database-user" }}
{{- $dbNameValue = index $secret.data "database-name" }}
{{- end -}}

apiVersion: v1
kind: Secret
metadata:
  annotations:
    template.openshift.io/expose-database_name: '{.data[''database-name'']}'
    template.openshift.io/expose-password: '{.data[''database-password'']}'
    template.openshift.io/expose-root_password: '{.data[''database-root-password'']}'
    template.openshift.io/expose-username: '{.data[''database-user'']}'
    argocd.argoproj.io/sync-wave: "1"
  name: mariadb
data:
  database-name: {{ $dbNameValue }}
  database-password: {{ $passwordValue }}
  database-root-password: {{ $rootPasswordValue }}
  database-user: {{ $dbUserValue }}