{{- $password := randAlphaNum 24 }}
{{- $rootPassword := randAlphaNum 24 }}

apiVersion: v1
kind: Secret
metadata:
  annotations:
    template.openshift.io/expose-database_name: '{.data[''database-name'']}'
    template.openshift.io/expose-password: '{.data[''database-password'']}'
    template.openshift.io/expose-root_password: '{.data[''database-root-password'']}'
    template.openshift.io/expose-username: '{.data[''database-user'']}'
    argocd.argoproj.io/sync-wave: "1"
  name: mariadb
stringData:
  database-name: {{ "mifosdb" | b64enc | quote }}
  database-password: {{ print $password | b64enc | quote }}
  database-root-password: {{ print $rootPassword | b64enc | quote }}
  database-user: {{ "mifosuser" | b64enc | quote}}