kind: ConfigMap
apiVersion: v1
metadata:
  name: mifos-db-config
  namespace: banking-demo
  annotations:
    argocd.argoproj.io/sync-wave: "1"
immutable: false
data:
  server-collation.cnf: |
    [client]
    default-character-set=utf8mb4

    [mysql]
    default-character-set=utf8mb4

    [mysqld]
    collation-server=utf8mb4_unicode_ci
    init-connect='SET NAMES utf8mb4'
    character-set-server=utf8mb4
  init.sql: |
    CREATE DATABASE IF NOT EXISTS `fineract_tenants`;
    CREATE DATABASE IF NOT EXISTS `fineract_default`;

    # create root user and grant rights
    GRANT ALL ON *.* TO 'root'@'%';
    GRANT ALL PRIVILEGES ON fineract_tenants.* TO 'mifosuser'@'%';
    GRANT ALL PRIVILEGES ON fineract_default.* TO 'mifosuser'@'%';
    FLUSH PRIVILEGES;