apiVersion: v1
kind: Secret
metadata:
  annotations:
    template.openshift.io/expose-database_name: '{.data[''database-name'']}'
    template.openshift.io/expose-password: '{.data[''database-password'']}'
    template.openshift.io/expose-root_password: '{.data[''database-root-password'']}'
    template.openshift.io/expose-username: '{.data[''database-user'']}'
    argocd.argoproj.io/sync-wave: "1"
  name: mariadb
  namespace: banking-demo
stringData:
  database-name: mifosdb
  database-password: securepassword
  database-root-password: secureRootPassword
  database-user: mifosuser