kind: ConfigMap
apiVersion: v1
metadata:
  name: mifos-web-app-config
  namespace: banking-demo
  annotations:
    argocd.argoproj.io/sync-wave: "1"
immutable: false
data:
  FINERACT_API_URLS: "https://fineract-route-banking-demo.apps.cnv.dxb.rhdxb.net"
  FINERACT_API_URL: "https://fineract-route-banking-demo.apps.cnv.dxb.rhdxb.net"
  FINERACT_API_PROVIDER: "/fineract-provider/api"
  FINERACT_API_VERSION: "/v1"
  FINERACT_PLATFORM_TENANT_IDENTIFIER: "default"
  MIFOS_DEFAULT_LANGUAGE: "en-US"
  MIFOS_SUPPORTED_LANGUAGES: "en-US,fr-FR"